############################################################
#
# web访问端口号  约定：8089
#
############################################################
server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  profiles:
    active: dev
#  datasource:                                             ## 数据源的相关配置
#    type: com.zaxxer.hikari.HikariDataSource              # 数据源 HikariCP
#    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动
#    url: jdbc:mysql://localhost:3306/itzixi-pay?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
#    username: root
#    password: root               # 本地数据库
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      #      <!-- 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count) -->
      # 如何计算 https://blog.csdn.net/X5fnncxzq4/article/details/80649679
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DatebookHikariCP     # 连接池名字
      max-lifetime: 28740000          # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms，建议设置比数据库超时时长少60秒，参考MySQL wait_timeout参数（show variables like '%timeout%';） -->
      connection-test-query: SELECT 1
  thymeleaf:
    mode: HTML
    encoding: utf-8
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  #  redis:                    ## Redis 相关配置
#    database: 1             # Redis数据库索引（默认为0）
#    host: 192.168.1.64     # 本地 Redis服务器地址
#    port: 6379              # 本地 Redis服务器连接端口
#    password: imooc


############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  #config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.imooc.pojo                     # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml                  # mapper映射文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  mappers: com.imooc.my.mapper.MyMapper
  not-empty: false
  identity: MYSQL
# 分页插件配置
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
params: count=countSql

wechat:
  appId: wx74862e0dfcf69954
  mchId: 1558950191
  mchKey: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
  notifyUrl: http://localhost:8087/notify
  keyPath:

alipay:
  appId: 2016092100561382
  privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDnJT5D4joj4vbIn/Vgs9oRR5iTLzkM+4bS7c60IWneN76Gh1jgpctiXYF5xhGuoEjTtRg+Xrx/EyJDwTwHYcgVbH9E8bIMFJTTMlTBsIeD8HHqKBQwVHyIz0Vv3cqHnNDP/rQZijW5tGxPxBF+bosireSBXsx36mZWfMlhLTPNzCSUWXzYliExMbpRwSUBfghFjjDx0G6m/8Wrl+UpIU2F7DiX72eGx4vtKT2hMYDA6mC6KNo5896sjjijFKYNyLRxdLgQCvxFw7w6R0L8MfTH+aQQlp3+9+izzMNlkGQGWj7n4m96iv7At0CvdlPJDZtoDdl56DzdvW07OxZUm7RlAgMBAAECggEAYxUe7MCEBbAb84JGEA7oknGrYKRkg0Eq2S4hZivQkvY4ULiiC6JmXaMRhl62Y7HHpiDB5LJ9gMd1769ciRmMSEq6/5XPqcgEx8eSd3ixjog6fJJznQgKXibjcAGV+K3rAM4A69XIE/PYXhUBHr5KHDKIekBly52KAtb5CBP1Weiw1ILquhAItIMiO+I2yoFNPLj3RG4/KVCLf962IVnr8MKyoNsAlcahtqSLvFinRiNhddijOr8zVvWvBfXQWCGfvgyDrTI9KaMsNgqu4Zwy5NVFiwEWCod0lDZHeLR4A/rYfBiM6//FUkdB9wMtNoauBMPI6Y8WHCNqyEuJdam+/QKBgQDzsLI0PI5rYMLTj/GHDZqj1u4ZYuHsNhFDHS+nDESO/SH+DKN2jsCdQ1dS7l3VuVHV0GgoDyHYQkNLF5NXAge8ueXZDp/+gl/7LD+WHYgWzJd+XR4XMtvQ6Xyyfju98updgfbk3tUtikWMm1yz8XAzp3YZud1YTJNwOfRd/cOL5wKBgQDy0lLYHWBcDy8Y6/Y2N69hR2l6+RtdjFqo70pTdDARMDyyj56Ppf5aVdFZLjnZ3HXDdrk9vcZ13Fh801BVvoGzOH1i9V8yQL1JZTq0292A6i+5UDqdfbyn4bAWmWHRqEiJhE9spBsQdnRvW6afFq8f0pUzUBp/IfxRFJLk+uDT0wKBgFyisct7raQR/13PHUB6omtf29kYpstVblB1+tRkrHcysMZTZZw+/eeKXtqutEr3jK1b8QwxXGtKHSyhhKgRpIFQpZhSn+1vAC+KDY3yIfaQxZIKsdKdycPrzjRIGkvF2OO88O7l6mHKa0/dC2t3/3ATW6jB5+uWCIIj9cn5GmnHAoGBAMpjQ2meEpKolTjQc4b9ItCSFPjKaGSwd2AXEnw8e1PYQL8TtbVFRZtFrBgIz28msYEZk4xCgQf7gEWKW4scHj6i9t9kZNQd4acrGKNmHlk02FI87J4YDwZetcYgUcfN26fC//AtV+GA2ct3OImg/pYnjvQV7//G8+cgns77zCjBAoGATm83LW++7LfMXDP2mlcm5gANHQxZQY1xIZzSLE6VW2h6+ZCpHi7OdrQ8n4n/cUPGnvnjrPTEzr3fSiMQO7k0Al+2s/HW7r35s/rIiINAVNu9sPTIU/hKuzQjGrsU2zWhd/KjlRfWx0rgw514rbxBYZU+3pXGwrzYhKBzYybFZVU=
  aliPayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoC35eTMWWVX0Lh7a5vQyEbmH2NbstXZ+JYE8Gkq5nCNQNuvSvHDvWxoz07TuY0ucCaI+gb1dTu8bNBSJFKxYWmGeb6WyPxH4OCGcstRUBDX/PtAa+CPfmzeWaTl//tA2CqXPzLNEvP1qiZdI/8v5yb/fRgxBqun/+xkEAsoq00k5BNZJ9QT6sCz/naM7EtKVJ5PHIddfZWUHNNBbpEnNzlE/+ZR7/tvrlBxWFSP3khbi9+OYPjnsJOWVgB8SLKsu8t8Eh/bTwxlelmHrPmWdk+qVdGSa3ccUjtohlj/MtYdNARXeF0FOw2sRhWEOoVwuB5d/aQvXNCgvXJ5HieFzewIDAQAB
  protocol: https
  gatewayHost: openapi.alipaydev.com
  signType: RSA2
  notifyUrl: http://bgssf7.natappfree.cc/payment/notice/alipay

